const fs = require('fs');

const data = {
  en: { choosePlan: 'Choose Your Plan', foreverFree: 'Forever free', currentDefault: 'Current Default', ourDoctors: 'Our Doctors', verifiedPros: 'Verified Healthcare Professionals', sessions: 'sessions', session: 'session', myConsultations: 'My Consultations', join: 'Join', bookConsultationTitle: 'Book Consultation', withDoctor: 'with', dateTime: 'Date & Time', describeConcern: 'Describe your concern (optional)', confirmBooking: 'Confirm Booking', bmDesc: 'Click on any body part to see related symptoms.', bmInstruction: 'Select a body part on the map to explore symptoms.', relatedFound: 'related symptoms found', commonSymptoms: 'Common Symptoms in this Area', bmPlaceholder: 'Select a body part on the map to explore symptoms.', interactiveLabel: 'Interactive' },
  bn: { choosePlan: 'আপনার প্ল্যান বেছে নিন', foreverFree: 'আজীবন ফ্রি', currentDefault: 'বর্তমান ডিফল্ট', ourDoctors: 'আমাদের ডাক্তারগণ', verifiedPros: 'যাচাইকৃত স্বাস্থ্য পেশাদার', sessions: 'সেশন', session: 'সেশন', myConsultations: 'আমার পরামর্শসমূহ', join: 'যোগ দিন', bookConsultationTitle: 'পরামর্শ বুক করুন', withDoctor: 'সাথে', dateTime: 'তারিখ ও সময়', describeConcern: 'আপনার সমস্যা বর্ণনা করুন (ঐচ্ছিক)', confirmBooking: 'বুকিং নিশ্চিত করুন', bmDesc: 'সম্পর্কিত লক্ষণগুলো দেখতে যেকোনো অংশে ক্লিক করুন।', bmInstruction: 'লক্ষণগুলো দেখতে মানচিত্র থেকে শরীরের একটি অংশ নির্বাচন করুন।', relatedFound: 'টি সম্পর্কিত লক্ষণ পাওয়া গেছে', commonSymptoms: 'এই এলাকার সাধারণ লক্ষণসমূহ', bmPlaceholder: 'লক্ষণগুলো দেখতে মানচিত্র থেকে শরীরের একটি অংশ নির্বাচন করুন।', interactiveLabel: 'ইন্টারঅ্যাক্টিভ' },
  hi: { choosePlan: 'अपनी योजना चुनें', foreverFree: 'हमेशा के लिए मुफ़्त', currentDefault: 'वर्तमान डिफ़ॉल्ट', ourDoctors: 'हमारे डॉक्टर', verifiedPros: 'सत्यापित स्वास्थ्य पेशेवर', sessions: 'सत्र', session: 'सत्र', myConsultations: 'मेरे परामर्श', join: 'शामिल हों', bookConsultationTitle: 'परामर्श बुक करें', withDoctor: 'के साथ', dateTime: 'तारीख और समय', describeConcern: 'अपनी समस्या का वर्णन करें (वैकल्पिक)', confirmBooking: 'बुकिंग की पुष्टि करें', bmDesc: 'संबंधित लक्षण देखने के लिए किसी भी अंग पर क्लिक करें।', bmInstruction: 'लक्षणों का पता लगाने के लिए नक्शे पर शरीर के एक अंग का चयन करें।', relatedFound: 'संबंधित लक्षण मिले', commonSymptoms: 'इस क्षेत्र में सामान्य लक्षण', bmPlaceholder: 'लक्षणों का पता लगाने के लिए शरीर के एक अंग का चयन करें।', interactiveLabel: 'इंटरैक्टिव' },
  es: { choosePlan: 'Elige tu plan', foreverFree: 'Gratis para siempre', currentDefault: 'Por defecto actual', ourDoctors: 'Nuestros Doctores', verifiedPros: 'Profesionales de salud verificados', sessions: 'sesiones', session: 'sesión', myConsultations: 'Mis Consultas', join: 'Unirse', bookConsultationTitle: 'Reservar Consulta', withDoctor: 'con', dateTime: 'Fecha y Hora', describeConcern: 'Describa su problema (opcional)', confirmBooking: 'Confirmar Reserva', bmDesc: 'Haga clic en cualquier parte del cuerpo para ver los síntomas.', bmInstruction: 'Seleccione una parte del cuerpo en el mapa para explorar los síntomas.', relatedFound: 'síntomas relacionados encontrados', commonSymptoms: 'Síntomas comunes en esta área', bmPlaceholder: 'Seleccione una parte del cuerpo en el mapa.', interactiveLabel: 'Interactivo' },
  fr: { choosePlan: 'Choisissez votre plan', foreverFree: 'Gratuit pour toujours', currentDefault: 'Défaut actuel', ourDoctors: 'Nos Médecins', verifiedPros: 'Professionnels de santé vérifiés', sessions: 'sessions', session: 'session', myConsultations: 'Mes Consultations', join: 'Rejoindre', bookConsultationTitle: 'Réserver une consultation', withDoctor: 'avec', dateTime: 'Date & Heure', describeConcern: 'Décrivez votre problème (facultatif)', confirmBooking: 'Confirmer la réservation', bmDesc: 'Cliquez sur n\'importe quelle partie du corps pour voir les symptômes.', bmInstruction: 'Sélectionnez une partie du corps sur la carte pour explorer les symptômes.', relatedFound: 'symptômes associés trouvés', commonSymptoms: 'Symptômes fréquents dans cette zone', bmPlaceholder: 'Sélectionnez une partie du corps sur la carte.', interactiveLabel: 'Interactif' },
  ar: { choosePlan: 'اختر خطتك', foreverFree: 'مجاني للأبد', currentDefault: 'الافتراضي الحالي', ourDoctors: 'أطباؤنا', verifiedPros: 'متخصصون صحيون معتمدون', sessions: 'جلسات', session: 'جلسة', myConsultations: 'استشاراتي', join: 'انضم', bookConsultationTitle: 'حجز استشارة', withDoctor: 'مع', dateTime: 'التاريخ والوقت', describeConcern: 'صف مشكلتك (اختياري)', confirmBooking: 'تأكيد الحجز', bmDesc: 'انقر على أي جزء من الجسم لرؤية الأعراض.', bmInstruction: 'اختر جزءًا من الجسم على الخريطة لاستكشاف الأعراض.', relatedFound: 'أعراض ذات صلة وجدت', commonSymptoms: 'أعراض شائعة في هذه المنطقة', bmPlaceholder: 'اختر جزءًا من الجسم على الخريطة.', interactiveLabel: 'تفاعلي' },
  pt: { choosePlan: 'Escolha seu Plano', foreverFree: 'Gratuito para sempre', currentDefault: 'Padrão Atual', ourDoctors: 'Nossos Médicos', verifiedPros: 'Profissionais de saúde verificados', sessions: 'sessões', session: 'sessão', myConsultations: 'Minhas Consultas', join: 'Entrar', bookConsultationTitle: 'Agendar Consulta', withDoctor: 'com', dateTime: 'Data e Hora', describeConcern: 'Descreva seu problema (opcional)', confirmBooking: 'Confirmar Agendamento', bmDesc: 'Clique em qualquer parte do corpo para ver os sintomas.', bmInstruction: 'Selecione uma parte do corpo no mapa para explorar os sintomas.', relatedFound: 'sintomas relacionados encontrados', commonSymptoms: 'Sintomas comuns nesta área', bmPlaceholder: 'Selecione uma parte do corpo no mapa.', interactiveLabel: 'Interativo' },
  zh: { choosePlan: '选择您的套餐', foreverFree: '永久免费', currentDefault: '当前默认', ourDoctors: '我们的医生', verifiedPros: '经过验证的医疗专业人员', sessions: '次咨询', session: '次咨询', myConsultations: '我的咨询', join: '加入', bookConsultationTitle: '预约咨询', withDoctor: '与', dateTime: '日期和时间', describeConcern: '描述您的问题（可选）', confirmBooking: '确认预约', bmDesc: '点击身体的任何部位以查看相关症状。', bmInstruction: '在地图上选择一个身体部位以探索症状。', relatedFound: '个相关症状被发现', commonSymptoms: '该区域的常见症状', bmPlaceholder: '在地图上选择一个身体部位以探索症状。', interactiveLabel: '互动' },
  ja: { choosePlan: 'プランを選択', foreverFree: '永久無料', currentDefault: '現在のデフォルト', ourDoctors: '私たちの医師', verifiedPros: '検証済みの医療専門家', sessions: 'セッション', session: 'セッション', myConsultations: '私の診察', join: '参加', bookConsultationTitle: '診察を予約', withDoctor: 'と', dateTime: '日付と時刻', describeConcern: '問題について説明してください（任意）', confirmBooking: '予約を確認', bmDesc: '関連する症状を確認するには、体の部位をクリックしてください。', bmInstruction: 'マップ上で体の部位を選択して、症状を調べます。', relatedFound: 'つの関連症状が見つかりました', commonSymptoms: 'この領域の一般的な症状', bmPlaceholder: 'マップ上で体の部位を選択して、症状を調べます。', interactiveLabel: 'インタラクティブ' },
  de: { choosePlan: 'Wählen Sie Ihren Plan', foreverFree: 'Für immer kostenlos', currentDefault: 'Aktueller Standard', ourDoctors: 'Unsere Ärzte', verifiedPros: 'Verifizierte medizinische Fachkräfte', sessions: 'Sitzungen', session: 'Sitzung', myConsultations: 'Meine Konsultationen', join: 'Beitreten', bookConsultationTitle: 'Konsultation buchen', withDoctor: 'mit', dateTime: 'Datum & Uhrzeit', describeConcern: 'Beschreiben Sie Ihr Anliegen (optional)', confirmBooking: 'Buchung bestätigen', bmDesc: 'Klicken Sie auf ein Körperteil, um verwandte Symptome zu sehen.', bmInstruction: 'Wählen Sie ein Körperteil auf der Karte, um Symptome zu erkunden.', relatedFound: 'verwandte Symptome gefunden', commonSymptoms: 'Häufige Symptome in diesem Bereich', bmPlaceholder: 'Wählen Sie ein Körperteil auf der Karte aus.', interactiveLabel: 'Interaktiv' },
  ru: { choosePlan: 'Выберите свой план', foreverFree: 'Навсегда бесплатно', currentDefault: 'Текущий по умолчанию', ourDoctors: 'Наши врачи', verifiedPros: 'Проверенные медицинские специалисты', sessions: 'сеансов', session: 'сеанс', myConsultations: 'Мои консультации', join: 'Присоединиться', bookConsultationTitle: 'Забронировать консультацию', withDoctor: 'с', dateTime: 'Дата и время', describeConcern: 'Опишите вашу проблему (необязательно)', confirmBooking: 'Подтвердить бронирование', bmDesc: 'Нажмите на любую часть тела, чтобы увидеть связанные симптомы.', bmInstruction: 'Выберите часть тела на карте, чтобы изучить симптомы.', relatedFound: 'связанных симптомов найдено', commonSymptoms: 'Общие симптомы в этой области', bmPlaceholder: 'Выберите часть тела на карте.', interactiveLabel: 'Интерактивный' },
  sw: { choosePlan: 'Chagua Mpango Wako', foreverFree: 'Bure milele', currentDefault: 'Chaguo-msingi', ourDoctors: 'Madaktari Wetu', verifiedPros: 'Wataalamu wa afya waliothibitishwa', sessions: 'vikao', session: 'kikao', myConsultations: 'Ushauri Wangu', join: 'Jiunge', bookConsultationTitle: 'Weka Ushauri', withDoctor: 'na', dateTime: 'Tarehe na Wakati', describeConcern: 'Eleza tatizo lako (hiari)', confirmBooking: 'Thibitisha Kuhifadhi', bmDesc: 'Bonyeza sehemu yoyote ya mwili kuona dalili zinazohusiana.', bmInstruction: 'Chagua sehemu ya mwili kwenye ramani.', relatedFound: 'dalili zinazohusiana zimepatikana', commonSymptoms: 'Dalili za Kawaida hapa', bmPlaceholder: 'Chagua sehemu ya mwili kwenye ramani.', interactiveLabel: 'Inayoingiliana' }
};

let content = fs.readFileSync('./src/i18n/translations.js', 'utf8');

for (const lang of Object.keys(data)) {
  const values = data[lang];
  let injected = '';
  for (const k in values) {
    injected += `    ${k}: '${values[k].replace(/'/g, "\\'")}',\n`;
  }
  
  // Find the block for this language: `lang: {`
  const regex = new RegExp(`(${lang}:\\s*\\{[\\s\\S]*?)(^\\s*\\},|\\s*\\}\\s*(?:;|export))`, 'm');
  content = content.replace(regex, `$1${injected}$2`);
}

fs.writeFileSync('./src/i18n/translations.js', content);
console.log('Successfully updated translations.js with Teleconsultation and BodyMap labels');
